#---------------------
# Comment
#---------------------

# better without spacing
name: My-GithubActions-Basics
env: # global variables
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: 
      - master
  

jobs:
  my_testing:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello world in Testing!
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to test.
        echo Application name ${{ env.APPLICATION_NAME }}

    - name: Git clone my repo
      uses: actions/checkout@v3  # checkout repository to the GitHub Actions runner

    - name: List current folder
      run: ls -la

        
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing] # depends on
    env: # local variables
      VAR1: "Some local variable"
    
    steps:
    - name: Run a one-line script
      run: echo Hello world in Deploy! ${{ env.VAR1 }} ${{ env.LOCAL_VAR }}
      env:
        LOCAL_VAR: "Super Local var"
      
    - name: Printing Deployment package
      run: echo Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}

    - name: Test package if it is here 1
      run: aws --version

    - name: Test package if it is here 2
      run: zip --version
